apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: clapwebservice
  namespace: '435513429904'
  selfLink: /apis/serving.knative.dev/v1/namespaces/435513429904/services/clapwebservice
  uid: c2bd1cbb-8525-41be-8b06-057ba5bd9ff9
  resourceVersion: AAYlFGabDow
  generation: 1
  creationTimestamp: '2024-10-22T17:50:05.656578Z'
  labels:
    cloud.googleapis.com/location: europe-north1
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 497.0.0
    serving.knative.dev/creator: yann.cherdo@gmail.com
    serving.knative.dev/lastModifier: yann.cherdo@gmail.com
    run.googleapis.com/operation-id: 1555026a-7efd-4a59-a52e-ecc71125d53c
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://clapwebservice-435513429904.europe-north1.run.app","https://clapwebservice-wka45d24uq-lz.a.run.app"]'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: ueueoyuloc
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 497.0.0
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 435513429904-compute@developer.gserviceaccount.com
      containers:
      - image: europe-north1-docker.pkg.dev/claptextcosine-439417/cloud-run-source-deploy/clapwebservice:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 4G
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2024-10-22T17:50:11.275404Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2024-10-22T17:50:10.301920Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2024-10-22T17:50:11.246510Z'
  latestReadyRevisionName: clapwebservice-00001-6kv
  latestCreatedRevisionName: clapwebservice-00001-6kv
  traffic:
  - revisionName: clapwebservice-00001-6kv
    percent: 100
    latestRevision: true
  url: https://clapwebservice-wka45d24uq-lz.a.run.app
  address:
    url: https://clapwebservice-wka45d24uq-lz.a.run.app
